apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: app-migration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 278119224464.dkr.ecr.ap-south-1.amazonaws.com/app-migration/nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"